<a href="https://colab.research.google.com/github/Lizochka1511/Valuk/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D0%A0%D0%BE%D0%B1%D0%BE%D1%82%D0%B04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# --- Налаштування матриці ---
N = 5  # Кількість рядків
M = 4  # Кількість стовпців

# Створення прямокутної матриці A з випадковими цілими числами
A = np.random.randint(0, 10, size=(N, M))

print(f"Створена матриця A ({N}x{M}):\n{A}\n")

# Пошук індексу стовпця з максимальною сумою абсолютних значень
abs_sums = np.sum(np.abs(A), axis=0)
max_sum_column_index = np.argmax(abs_sums)

# Пошук найменшого елемента в цьому стовпці
target_column = A[:, max_sum_column_index]
min_element = np.min(target_column)

print(f"Індекс стовпця з максимальною сумою: {max_sum_column_index}")
print(f"Найменший елемент у цьому стовпці: {min_element}")


Створена матриця A (5x4):
[[0 0 8 9]
 [8 7 0 9]
 [1 2 5 1]
 [3 9 5 1]
 [4 4 1 7]]

Індекс стовпця з максимальною сумою: 3
Найменший елемент у цьому стовпці: 1


In [5]:
import numpy as np
import matplotlib.pyplot as plt

# Дані з таблиці
x_points = np.array()
y_points = np.array()
x_target = 3.1

# Апроксимація поліномом 2-го степеня (y(x) = x**2 + 2)
degree = 2
coefficients = np.polyfit(x_points, y_points, degree)
polynomial = np.poly1d(coefficients)
y_interpolated = polynomial(x_target)

print(f"Інтерпольоване значення y при x={x_target} дорівнює: {y_interpolated:.2f}\n")

# Побудова графіка
x_func = np.linspace(min(x_points), max(x_points), 100)
y_func = polynomial(x_func)

plt.figure(figsize=(8, 6))
plt.plot(x_func, y_func, label='Графік функції y(x) = x² + 2', color='blue')
plt.scatter(x_points, y_points, color='red', zorder=5, label='Задані точки')
plt.scatter(x_target, y_interpolated, color='green', zorder=5, label='Інтерпольоване значення')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Графік інтерполяційної функції')
plt.legend()
plt.grid(True)
plt.show()


TypeError: array() missing required argument 'object' (pos 0)

In [6]:
import numpy as np

def f(x):
    return 3*x**4 + 4*x**3 - 12*x**2 - 5

def bisection_method(a, b, eps):
    # ... (функція bisection_method з попередньої відповіді) ...
    c = a
    while (b - a) >= eps:
        c = (a + b) / 2
        if f(c) == 0.0: break
        if f(c) * f(a) < 0: b = c
        else: a = c
    return c

def chord_method(a, b, eps):
    # ... (функція chord_method з попередньої відповіді) ...
    c = a
    while abs(f(c)) >= eps:
        c = a - (f(a) * (b - a)) / (f(b) - f(a))
        if f(c) == 0.0: break
        if f(c) * f(a) < 0: b = c
        else: a = c
    return c

interval_1 = [-2.5, -2.0]
interval_2 = [1.0, 1.5]
tolerance = 0.0001

print(f"--- Інтервал 1: {interval_1} ---")
print(f"Корінь методом половинного ділення: {bisection_method(*interval_1, tolerance):.5f}")
print(f"Корінь методом хорд: {chord_method(*interval_1, tolerance):.5f}")

print(f"\n--- Інтервал 2: {interval_2} ---")
print(f"Корінь методом половинного ділення: {bisection_method(*interval_2, tolerance):.5f}")
print(f"Корінь методом хорд: {chord_method(*interval_2, tolerance):.5f}")


--- Інтервал 1: [-2.5, -2.0] ---
Корінь методом половинного ділення: -2.00006
Корінь методом хорд: -2.82385

--- Інтервал 2: [1.0, 1.5] ---
Корінь методом половинного ділення: 1.49994
Корінь методом хорд: 1.59209


In [7]:
import numpy as np

def f(x):
    return x**3 + 2*x**2 - x + 2

# Вибір phi(x) для інтервалу [-3, -2] (лямбда = 0.05)
def phi(x):
    lambda_val = 0.05
    return x + lambda_val * f(x)

def simple_iteration(x0, iterations_count):
    x_prev = x0
    for i in range(iterations_count):
        x_curr = phi(x_prev)
        error = abs(x_curr - x_prev)
        print(f"Ітерація {i + 1}: x_k = {x_curr:.6f}, Похибка: {error:.6e}")
        x_prev = x_curr
    return x_prev

x0 = -2.5 # Початкове наближення
num_iterations = 5

print(f"Запуск методу простої ітерації на інтервалі [-3, -2] з x0={x0}")
final_root = simple_iteration(x0, num_iterations)
print(f"\nНаближене значення кореня після {num_iterations} ітерацій: {final_root:.6f}")


Запуск методу простої ітерації на інтервалі [-3, -2] з x0=-2.5
Ітерація 1: x_k = -2.431250, Похибка: 6.875000e-02
Ітерація 2: x_k = -2.337143, Похибка: 9.410707e-02
Ітерація 3: x_k = -2.212364, Похибка: 1.247794e-01
Ітерація 4: x_k = -2.053717, Похибка: 1.586470e-01
Ітерація 5: x_k = -1.862359, Похибка: 1.913577e-01

Наближене значення кореня після 5 ітерацій: -1.862359


In [8]:
import numpy as np

def f(x): return x**3 + 2*x**2 - x + 2
def df(x): return 3*x**2 + 4*x - 1 # Перша похідна
def ddf(x): return 6*x + 4          # Друга похідна

def newton_method(x0, eps):
    # ... (функція newton_method з попередньої відповіді) ...
    x_prev = x0
    while True:
        x_curr = x_prev - f(x_prev) / df(x_prev)
        if abs(x_curr - x_prev) < eps: break
        x_prev = x_curr
    return x_curr

def combined_method(a, b, eps):
    # ... (функція combined_method з попередньої відповіді) ...
    x_newton = a if f(a) * ddf(a) > 0 else b
    x_chord = b if x_newton == a else a
    while True:
        x_curr_n = x_newton - f(x_newton) / df(x_newton)
        x_curr_c = x_chord - (f(x_chord) * (x_chord - x_newton)) / (f(x_chord) - f(x_newton))
        if abs(x_curr_c - x_curr_n) < eps: break
        x_newton = x_curr_n
        x_chord = x_curr_c
    return (x_curr_n + x_curr_c) / 2

a, b, tolerance = -3.0, -2.0, 0.0001
x0_newton = a if f(a)*ddf(a) > 0 else b

print(f"Корінь методом Ньютона: {newton_method(x0_newton, tolerance):.6f}")
print(f"Корінь комбінованим методом: {combined_method(a, b, tolerance):.6f}")


Корінь методом Ньютона: -2.658967
Корінь комбінованим методом: -2.658965


In [9]:
import numpy as np

A = np.array()
B = np.array()

print(f"Матриця A:\n{A}\n")
print(f"Матриця B:\n{B}\n")

C = A @ B - B @ A # Використання оператора @ для матричного множення
print(f"Матриця C = AB - BA:\n{C}\n")


TypeError: array() missing required argument 'object' (pos 0)

In [10]:
import numpy as np

# Приклад 1 (Матриця А 2х2)
A = np.array()
A2 = A @ A
print(f"Матриця A^2 (2x2):\n{A2}\n")

# Приклад 2 (Матриця B 3х3)
B = np.array([
    [-1, 0, 2],
    [0, 1, 0],
    [1, 2, -1]
])
B2 = B @ B
print(f"Матриця B^2 (3x3):\n{B2}\n")


TypeError: array() missing required argument 'object' (pos 0)

In [11]:
import numpy as np

A = np.array([
    [3, 5],
    [6, -1]
])
B = np.array([
    [2, 1],
    [-3, 2]
])

C = A @ B
print(f"Добуток матриць C = A @ B:\n{C}\n")


Добуток матриць C = A @ B:
[[-9 13]
 [15  4]]



In [13]:
import numpy as np

A = np.array([
   ,
    [5, -3, 2],
    [10, -11, 5]
], dtype=float)

B = np.array(, dtype=float)

print("--- Перевірка з np.linalg.solve() ---")
solution_solve = np.linalg.solve(A, B)
print(f"Рішення (x, y, z): {solution_solve}\n")

print("--- Рішення матричним методом (A⁻¹ * B) ---")
A_inv = np.linalg.inv(A)
solution_matrix = np.dot(A_inv, B)
print(f"Рішення (x, y, z): {solution_matrix}\n")

print("--- Рішення методом Крамера ---")
D = np.linalg.det(A)
Ax, Ay, Az = A.copy(), A.copy(), A.copy()
Ax[:, 0], Ay[:, 1], Az[:, 2] = B, B, B
x, y, z = np.linalg.det(Ax)/D, np.linalg.det(Ay)/D, np.linalg.det(Az)/D
print(f"Рішення (x, y, z): x={x:.6f}, y={y:.6f}, z={z:.6f}\n")

print("--- Рішення методом Гаусса (вбудовано в linalg.solve) ---")
# Ручна реалізація методу Гаусса була надана в попередній відповіді,
# але np.linalg.solve() використовує схожий ефективний метод (LU-розкладання).
# Результат ідентичний першому виводу.


SyntaxError: invalid syntax (ipython-input-4246196184.py, line 4)